export const countries = [
  { name: "United Arab Emirates", capital: "Abu Dhabi", phone: "971" },
  { name: "Afghanistan", capital: "Kabul", phone: "93" },
  { name: "Antigua and Barbuda", capital: "Saint John's", phone: "1268" },
  { name: "Angola", capital: "Luanda", phone: "244" },
  { name: "Antarctica", capital: null, phone: "672" },
  { name: "Argentina", capital: "Buenos Aires", phone: "54" },
  { name: "American Samoa", capital: "Pago Pago", phone: "1684" },
  { name: "Austria", capital: "Vienna", phone: "43" },
  { name: "Australia", capital: "Canberra", phone: "61" },
  { name: "Aruba", capital: "Oranjestad", phone: "297" },
  { name: "Åland", capital: "Mariehamn", phone: "358" },
  { name: "Azerbaijan", capital: "Baku", phone: "994" },
  { name: "Bosnia and Herzegovina", capital: "Sarajevo", phone: "387" },
  { name: "Barbados", capital: "Bridgetown", phone: "1246" },
  { name: "Bangladesh", capital: "Dhaka", phone: "880" },
  { name: "Belgium", capital: "Brussels", phone: "32" },
  { name: "Burkina Faso", capital: "Ouagadougou", phone: "226" },
  { name: "Bulgaria", capital: "Sofia", phone: "359" },
  { name: "Bahrain", capital: "Manama", phone: "973" },
  { name: "Burundi", capital: "Bujumbura", phone: "257" },
  { name: "Benin", capital: "Porto-Novo", phone: "229" },
  { name: "Saint Barthélemy", capital: "Gustavia", phone: "590" },
  { name: "Bermuda", capital: "Hamilton", phone: "1441" },
];
